{% set name = "maxminddb" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c5b91c62bc274d0a83ac88088a6db2dac1301acb8aa7bf80a901a07120361e1d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - maxminddb

about:
  home: https://pypi.org/project/maxminddb/#description
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: This is a Python module for reading MaxMind DB files

extra:
  recipe-maintainers:
    - rverma129
