{% set name = "maxminddb" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9792b19625945dff146e2e3187f9e470b82330a912f7cea5581b8bd5af30da8b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8

test:
  imports:
    - maxminddb

about:
  home: https://pypi.org/project/maxminddb/#description
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: This is a Python module for reading MaxMind DB files

extra:
  recipe-maintainers:
    - rverma129
