{% set name = "maxminddb" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 23a715ed3b3aed07adae4beeed06c51fd582137b5ae13d3c6e5ca4890f70ebbf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8

test:
  imports:
    - maxminddb

about:
  home: https://pypi.org/project/maxminddb/#description
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: This is a Python module for reading MaxMind DB files

extra:
  recipe-maintainers:
    - rverma129
