{% set name = "maxminddb" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 47e86a084dd814fac88c99ea34ba3278a74bc9de5a25f4b815b608798747c7dc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - maxminddb

about:
  home: https://pypi.org/project/maxminddb/#description
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: This is a Python module for reading MaxMind DB files

extra:
  recipe-maintainers:
    - rverma129
